### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/celebA/list_attr_celeba.txt'

### ISSUE THREAD

**Issue by akkshita** [timsainb/GAIA#1]
hello
i have run that link also after download all thing using that link this error is occur

FileNotFoundError: [Errno 2] No such file or directory: 'data/celebA/list_attr_celeba.txt'

**Comment by timsainb** [comment]
I'm not sure what went wrong for you, but the file is still hosted in the same place:
https://drive.google.com/file/d/0B7EVK8r0v71pblRyaVFSWGxPY0U/view
Just place it in the right directory.

**Comment by akkshita** [comment]
Hello,
In this line 

for file_7z in np.sort(glob.glob(dirpath+'img_celeba.7z*')):
    !7z x $file_7z  -o$ outpath



this error is occur

/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found
/bin/sh: 1: 7z: not found

**Comment by dvalenciar** [comment]
hello, I got the same error as @akkshita  seem that  the link is broken or the file does not excite anymore

**Comment by timsainb** [comment]
I have used this repo to build the dataset in more recent projects: https://github.com/switchablenorms/CelebAMask-HQ

Same dataset, with some extra annotation, and you don't have to build it yourself. 
__
