### ISSUE TITLE
Questions in the paper

### ISSUE THREAD

**Issue by Abel1802** [timsainb/GAIA#3]
Excuse me, I have a question to ask.
In your paper:
"The linear interpolations are Euclidean interpolations between pairs of points in Z, sampled from a 1-dimensional Gaussian distribution5 centered around the midpoint between zgeni and zgenj ."
In other words, it requires two latent representations.

But in your code:
The function of "get_midpoints(z, midpoint_div_1, midpoint_div_2)" in the network.py (line 502) only one latent representation is passed in.

There is a screenshot below that describes my problem. Thank you!
![code](https://user-images.githubusercontent.com/55339089/98625176-19109000-234a-11eb-858f-438ba76e684f.jpg)

**Comment by timsainb** [comment]
Hi @Abel1802 the tf.slice function is cutting the batch z into two batches first_half_batch and second_half_batch, then interpolating between them.

**Comment by Abel1802** [comment]
I thought that picture 1 and picture 2 are a pair, which turned out to be half of batch. thank you
